// source: proto/shop/v1/shop.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.shop.UpdateShopInfoRequest');
goog.provide('proto.shop.UpdateShopInfoRequest.UpdateShopInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.Timestamp');
goog.require('proto.shop.Address');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shop.UpdateShopInfoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.shop.UpdateShopInfoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shop.UpdateShopInfoRequest.displayName = 'proto.shop.UpdateShopInfoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.shop.UpdateShopInfoRequest.UpdateShopInfo.repeatedFields_, null);
};
goog.inherits(proto.shop.UpdateShopInfoRequest.UpdateShopInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shop.UpdateShopInfoRequest.UpdateShopInfo.displayName = 'proto.shop.UpdateShopInfoRequest.UpdateShopInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shop.UpdateShopInfoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.shop.UpdateShopInfoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shop.UpdateShopInfoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shop.UpdateShopInfoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    updateShopInfo: (f = msg.getUpdateShopInfo()) && proto.shop.UpdateShopInfoRequest.UpdateShopInfo.toObject(includeInstance, f),
    openDatetime: (f = msg.getOpenDatetime()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    closeDatetime: (f = msg.getCloseDatetime()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shop.UpdateShopInfoRequest}
 */
proto.shop.UpdateShopInfoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shop.UpdateShopInfoRequest;
  return proto.shop.UpdateShopInfoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shop.UpdateShopInfoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shop.UpdateShopInfoRequest}
 */
proto.shop.UpdateShopInfoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.shop.UpdateShopInfoRequest.UpdateShopInfo;
      reader.readMessage(value,proto.shop.UpdateShopInfoRequest.UpdateShopInfo.deserializeBinaryFromReader);
      msg.setUpdateShopInfo(value);
      break;
    case 3:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setOpenDatetime(value);
      break;
    case 4:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setCloseDatetime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shop.UpdateShopInfoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shop.UpdateShopInfoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shop.UpdateShopInfoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shop.UpdateShopInfoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getUpdateShopInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.shop.UpdateShopInfoRequest.UpdateShopInfo.serializeBinaryToWriter
    );
  }
  f = message.getOpenDatetime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCloseDatetime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.shop.UpdateShopInfoRequest.UpdateShopInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    address: (f = msg.getAddress()) && proto.shop.Address.toObject(includeInstance, f),
    sisterShopsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo}
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shop.UpdateShopInfoRequest.UpdateShopInfo;
  return proto.shop.UpdateShopInfoRequest.UpdateShopInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo}
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.shop.Address;
      reader.readMessage(value,proto.shop.Address.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedUint64() : [reader.readUint64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSisterShops(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shop.UpdateShopInfoRequest.UpdateShopInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.shop.Address.serializeBinaryToWriter
    );
  }
  f = message.getSisterShopsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      3,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo} returns this
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Address address = 2;
 * @return {?proto.shop.Address}
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.getAddress = function() {
  return /** @type{?proto.shop.Address} */ (
    jspb.Message.getWrapperField(this, proto.shop.Address, 2));
};


/**
 * @param {?proto.shop.Address|undefined} value
 * @return {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo} returns this
*/
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.setAddress = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo} returns this
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.clearAddress = function() {
  return this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated uint64 sister_shops = 3;
 * @return {!Array<number>}
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.getSisterShopsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo} returns this
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.setSisterShopsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo} returns this
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.addSisterShops = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shop.UpdateShopInfoRequest.UpdateShopInfo} returns this
 */
proto.shop.UpdateShopInfoRequest.UpdateShopInfo.prototype.clearSisterShopsList = function() {
  return this.setSisterShopsList([]);
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.shop.UpdateShopInfoRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.shop.UpdateShopInfoRequest} returns this
 */
proto.shop.UpdateShopInfoRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional UpdateShopInfo update_shop_info = 2;
 * @return {?proto.shop.UpdateShopInfoRequest.UpdateShopInfo}
 */
proto.shop.UpdateShopInfoRequest.prototype.getUpdateShopInfo = function() {
  return /** @type{?proto.shop.UpdateShopInfoRequest.UpdateShopInfo} */ (
    jspb.Message.getWrapperField(this, proto.shop.UpdateShopInfoRequest.UpdateShopInfo, 2));
};


/**
 * @param {?proto.shop.UpdateShopInfoRequest.UpdateShopInfo|undefined} value
 * @return {!proto.shop.UpdateShopInfoRequest} returns this
*/
proto.shop.UpdateShopInfoRequest.prototype.setUpdateShopInfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shop.UpdateShopInfoRequest} returns this
 */
proto.shop.UpdateShopInfoRequest.prototype.clearUpdateShopInfo = function() {
  return this.setUpdateShopInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shop.UpdateShopInfoRequest.prototype.hasUpdateShopInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp open_datetime = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.shop.UpdateShopInfoRequest.prototype.getOpenDatetime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.shop.UpdateShopInfoRequest} returns this
*/
proto.shop.UpdateShopInfoRequest.prototype.setOpenDatetime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shop.UpdateShopInfoRequest} returns this
 */
proto.shop.UpdateShopInfoRequest.prototype.clearOpenDatetime = function() {
  return this.setOpenDatetime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shop.UpdateShopInfoRequest.prototype.hasOpenDatetime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp close_datetime = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.shop.UpdateShopInfoRequest.prototype.getCloseDatetime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.shop.UpdateShopInfoRequest} returns this
*/
proto.shop.UpdateShopInfoRequest.prototype.setCloseDatetime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shop.UpdateShopInfoRequest} returns this
 */
proto.shop.UpdateShopInfoRequest.prototype.clearCloseDatetime = function() {
  return this.setCloseDatetime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shop.UpdateShopInfoRequest.prototype.hasCloseDatetime = function() {
  return jspb.Message.getField(this, 4) != null;
};


