// source: proto/shop/v1/shop.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.shop.UpdateShopInfoResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.shop.ShopInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shop.UpdateShopInfoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.shop.UpdateShopInfoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shop.UpdateShopInfoResponse.displayName = 'proto.shop.UpdateShopInfoResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shop.UpdateShopInfoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.shop.UpdateShopInfoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shop.UpdateShopInfoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shop.UpdateShopInfoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    shopInfo: (f = msg.getShopInfo()) && proto.shop.ShopInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shop.UpdateShopInfoResponse}
 */
proto.shop.UpdateShopInfoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shop.UpdateShopInfoResponse;
  return proto.shop.UpdateShopInfoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shop.UpdateShopInfoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shop.UpdateShopInfoResponse}
 */
proto.shop.UpdateShopInfoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.shop.ShopInfo;
      reader.readMessage(value,proto.shop.ShopInfo.deserializeBinaryFromReader);
      msg.setShopInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shop.UpdateShopInfoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shop.UpdateShopInfoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shop.UpdateShopInfoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shop.UpdateShopInfoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShopInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.shop.ShopInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional ShopInfo shop_info = 1;
 * @return {?proto.shop.ShopInfo}
 */
proto.shop.UpdateShopInfoResponse.prototype.getShopInfo = function() {
  return /** @type{?proto.shop.ShopInfo} */ (
    jspb.Message.getWrapperField(this, proto.shop.ShopInfo, 1));
};


/**
 * @param {?proto.shop.ShopInfo|undefined} value
 * @return {!proto.shop.UpdateShopInfoResponse} returns this
*/
proto.shop.UpdateShopInfoResponse.prototype.setShopInfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shop.UpdateShopInfoResponse} returns this
 */
proto.shop.UpdateShopInfoResponse.prototype.clearShopInfo = function() {
  return this.setShopInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shop.UpdateShopInfoResponse.prototype.hasShopInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


